FROM openjdk:8u191-jre-alpine3.9

RUN apk add curl jq
# Wo
WORKDIR /usr/share/udemy

# ADD .jars under target from host
# into this image
ADD target/selenium-docker.jar        selenium-docker.jar
ADD target/selenium-docker-tests.jar  selenium-docker-tests.jar
ADD target/libs                       libs

# in case of any other dependencies like .csv .json .xls
# please ADD that as well

#Add suit files
ADD book-flight.xml                   book-flight.xml

# health check script
ADD healthcheck.sh                    healthcheck.sh

# BROWSER
# HUB_HOST
# MODULE

#ENTRYPOINT java -cp selenium-docker.jar:selenium-docker-tests.jar:libs/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
ENTRYPOINT sh healthcheck.sh